using System.Collections.Generic;
using Godot;

/// The character ROM the OSD and the receiver's own text are drawn from.
///
/// **Every number here is measured off the pilot's own footage**, frame by frame at 1:1, and the whole point is that
/// the result is indistinguishable from it. The footage itself is OPSEC-restricted and never enters the repo; what is
/// recorded below is geometry — cell size, glyph size, stroke weight — and nothing that was written on the screen.
///
/// Measured at 1920 × 1080 (see FeedOsd for the grid the cell sits in, 67.3 × 71 px):
///
/// | | footage | this ROM |
/// |---|---|---|
/// | glyph ink width | 23–24 px | 5/14 of the cell = 24.0 px |
/// | glyph ink height | 29–30 px | 8/18 of the cell = 31.6 px |
/// | vertical stroke | 5–6 px | 1/14 of the cell = 4.8 px |
/// | horizontal stroke | 3 px | 1/18 of the cell = 3.9 px |
/// | outline | 4–5 px | one cell sample, so the same |
///
/// So the letterform is **5 × 8 samples inside a 14 × 18 cell** — small, narrow and widely spaced, which is what makes
/// a character OSD read as one. Filling the cell the way a UI font does is the single thing that made the earlier
/// version look like a game HUD. Icons are authored at their own size (the battery is 10 × 14, the labels wider and
/// shorter) and centred in the same cell, exactly as a character generator's ROM holds them.
///
/// Nothing is scaled up on the way into the atlas: one authored sample is one atlas texel, and the feed's own
/// transmission path is what softens the edges afterwards (P2, P4). The outline is one texel, generated by dilation.
public static class FeedFont
{
    /// The character cell, in atlas texels. It maps to the 67.3 × 71 px cell FeedOsd lays out.
    public const int CellW = 14, CellH = 18;

    /// One entry per character: the character, a space, then its rows, `#` ink and `.` blank. A glyph may be any size
    /// up to the cell and is centred in it. Letters and digits are 5 × 8; the icons are wider or shorter.
    /// The order is the atlas order, and a character's code is its index here plus one.
    static readonly string[] Glyphs =
    {
        "0 .###. #...# #...# #...# #...# #...# #...# .###.",
        "1 ..#.. .##.. ..#.. ..#.. ..#.. ..#.. ..#.. .###.",
        "2 .###. #...# ....# ...#. ..#.. .#... #.... #####",
        "3 ##### ...#. ..##. ....# ....# #...# #...# .###.",
        "4 ...#. ..##. .#.#. #..#. ##### ...#. ...#. ...#.",
        "5 ##### #.... #.... ####. ....# ....# #...# .###.",
        "6 ..##. .#... #.... ####. #...# #...# #...# .###.",
        "7 ##### ....# ...#. ...#. ..#.. ..#.. .#... .#...",
        "8 .###. #...# #...# .###. #...# #...# #...# .###.",
        "9 .###. #...# #...# #...# .#### ....# ...#. .##..",
        "A .###. #...# #...# #...# ##### #...# #...# #...#",
        "B ####. #...# #...# ####. #...# #...# #...# ####.",
        "C .###. #...# #.... #.... #.... #.... #...# .###.",
        "D ####. #...# #...# #...# #...# #...# #...# ####.",
        "E ##### #.... #.... ####. #.... #.... #.... #####",
        "F ##### #.... #.... ####. #.... #.... #.... #....",
        "G .###. #...# #.... #.... #.### #...# #...# .####",
        "H #...# #...# #...# ##### #...# #...# #...# #...#",
        // The footage draws I as a plain bar with no serifs: one sample wide over the full height.
        "I ..#.. ..#.. ..#.. ..#.. ..#.. ..#.. ..#.. ..#..",
        "J ..### ...#. ...#. ...#. ...#. ...#. #..#. .##..",
        "K #...# #..#. #.#.. ##... ##... #.#.. #..#. #...#",
        "L #.... #.... #.... #.... #.... #.... #.... #####",
        "M #...# ##.## #.#.# #.#.# #...# #...# #...# #...#",
        "N #...# ##..# ##..# #.#.# #.#.# #..## #..## #...#",
        "O .###. #...# #...# #...# #...# #...# #...# .###.",
        "P ####. #...# #...# #...# ####. #.... #.... #....",
        "Q .###. #...# #...# #...# #...# #.#.# #..#. .##.#",
        "R ####. #...# #...# #...# ####. #.#.. #..#. #...#",
        "S .###. #...# #.... .###. ....# ....# #...# .###.",
        "T ##### ..#.. ..#.. ..#.. ..#.. ..#.. ..#.. ..#..",
        "U #...# #...# #...# #...# #...# #...# #...# .###.",
        "V #...# #...# #...# #...# #...# #...# .#.#. ..#..",
        "W #...# #...# #...# #...# #.#.# #.#.# ##.## #...#",
        "X #...# #...# .#.#. ..#.. ..#.. .#.#. #...# #...#",
        "Y #...# #...# .#.#. ..#.. ..#.. ..#.. ..#.. ..#..",
        "Z ##### ....# ...#. ..#.. ..#.. .#... #.... #####",
        // The unit marks are the only small characters: they sit low in the cell, as in the footage.
        "m ..... ..... ..... ##.#. #.#.# #.#.# #.#.# #.#.#",
        "a ..... ..... ..... .###. ....# .#### #...# .####",
        "в ..... ..... ..... ####. #...# ####. #...# ####.",
        "! ..#.. ..#.. ..#.. ..#.. ..#.. ..#.. ..... ..#..",
        ". ..... ..... ..... ..... ..... ..... ..##. ..##.",
        ": ..... ..##. ..##. ..... ..... ..##. ..##. .....",
        "- ..... ..... ..... ..... ##### ..... ..... .....",
        // The battery mark that leads each voltage readout: 10 x 14 in the cell, measured 45 x 62 px on the footage.
        // A cap, a rim, a hollow upper part and a solid lower one.
        "$ ...####... ########## #........# #........# #........# #........# #........# ########## ########## ########## ########## ########## ########## ##########",
        // The altitude label: three small letters inside one cell, 11 x 5, measured 49 x 18 px.
        "> .#..#...### #.#.#....#. ###.#....#. #.#.#....#. #.#.###..#.",
        // The two-line unit label beside the flight timer, 7 x 9, measured 33 x 37 px. The footage's label is text,
        // but its content is not recorded (OPSEC), so these two tiny lines are invented.
        "[ ###.#.. #...#.. ##..#.. #...### ....... ###.#.# .#..### .#..#.# .#..#.#",
        // The centre reticle, three cells wide: a stub, the bar with its lozenge, and a stub. Measured on the
        // footage as a 100 px bar, one sample thick, with a 28 x 14 px lozenge at the middle.
        "{ .............. ...........### ..............",
        "| ....######.... #####.....#### ....######....",
        "} .............. ####.......... ..............",
    };

    static readonly Dictionary<char, float> Codes = Build();

    /// The number of cells in the atlas, blank included. The shader needs it to index a cell.
    public static int CellCount => Glyphs.Length + 1;

    /// The atlas cell of a character, 0 (blank) for a space or anything the ROM does not have.
    public static float Code(char c) => Codes.TryGetValue(c, out float code) ? code : 0f;

    static Dictionary<char, float> Build()
    {
        var codes = new Dictionary<char, float>(Glyphs.Length);
        for (int i = 0; i < Glyphs.Length; i++)
            codes[Glyphs[i][0]] = i + 1;
        return codes;
    }

    /// Bakes the atlas: one row of CellCount cells, R the glyph and G its one-texel outline.
    public static ImageTexture BuildAtlas()
    {
        int w = CellCount * CellW;
        var ink = new bool[w, CellH];
        for (int g = 0; g < Glyphs.Length; g++)
        {
            string[] rows = Glyphs[g].Substring(2).Split(' ');
            int gw = rows[0].Length, gh = rows.Length;
            int x0 = (g + 1) * CellW + (CellW - gw) / 2, y0 = (CellH - gh) / 2;
            for (int y = 0; y < gh; y++)
                for (int x = 0; x < gw; x++)
                    if (rows[y][x] == '#')
                        ink[x0 + x, y0 + y] = true;
        }

        var img = Image.CreateEmpty(w, CellH, false, Image.Format.Rg8);
        for (int y = 0; y < CellH; y++)
            for (int x = 0; x < w; x++)
            {
                bool on = ink[x, y];
                bool outline = false;
                if (!on)
                {
                    // Dilate by one texel, but never across a cell boundary, or a glyph would outline its neighbour.
                    int cellStart = x / CellW * CellW;
                    for (int dy = -1; dy <= 1 && !outline; dy++)
                        for (int dx = -1; dx <= 1; dx++)
                        {
                            int nx = x + dx, ny = y + dy;
                            if (ny < 0 || ny >= CellH || nx < cellStart || nx >= cellStart + CellW || !ink[nx, ny])
                                continue;
                            outline = true;
                            break;
                        }
                }
                img.SetPixel(x, y, new Color(on ? 1f : 0f, outline ? 1f : 0f, 0f));
            }
        return ImageTexture.CreateFromImage(img);
    }
}
